env:
    configs: {}
    contexts:
        - authentication:
            method: manual
            verification:
                loggedInRegex: (access_token)
                method: response
                pollFrequency: 60
                pollUnits: requests
                pollUrl: ""
          excludePaths:
            - https://devsecops360.fusion.co.th/logout.*
          includePaths:
            - https://devsecops360.fusion.co.th.*
          name: DevSecOps360
          structure: {}
          technology: {}
          urls:
            - https://devsecops360.fusion.co.th
          users:
            - credentials: {}
              name: svc-devsecops360
    parameters:
        failOnError: true
        failOnWarning: false
        progressToStdout: true
jobs:
    - parameters: {}
      type: passiveScan-config
    - parameters:
        context: DevSecOps360
        maxDuration: 5
        user: svc-devsecops360
      type: spider
    - parameters: {}
      type: passiveScan-wait
    - parameters:
        context: DevSecOps360
        policyDefinition: {}
        user: svc-devsecops360
      type: activeScan
    - parameters:
        reportDir: /tmp/dast-output-3401091979
        reportFile: ZAP-Report
        reportTitle: ZAP by Checkmarx - DevSecOps360
        template: traditional-json-plus
      type: report
    - parameters: {}
      type: exitStatus
    - name: export
      parameters:
        fileName: /tmp/dast-output-3401091979/ZAP-Sites-Tree.yaml
        source: sitestree
        type: yaml
      type: export
